name: Deploy Angular app to GitHub Pages

on:
  push:
    branches:
      - main    # cambia se il branch principale ha un altro nome

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build-and-deploy:
    environment:
      name: github-pages
      url: ${{ steps.deploy.outputs.page_url }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Build Angular app
        run: |
          npm run build -- --base-href /sito-ripetizioni/
          cp dist/aura-math/index.html dist/aura-math/404.html

      - name: Setup GitHub Pages
        uses: actions/configure-pages@v4

      - name: Upload build artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: dist/aura-math

      - name: Deploy to GitHub Pages
        id: deploy
        uses: actions/deploy-pages@v4
